In [6]:
import numpy as np

matrix_a = np.array([[2,3,1],[-1,1,0],[1,2,-1]])
matrix_b = np.array([[1,2,1],[0,1,2],[3,1,1]])

matrix_c = matrix_a.dot(matrix_b) - matrix_b.dot(matrix_a)

print(matrix_c)

[[ 4  1  9]
 [-2 -6  3]
 [-8 -9  2]]


In [8]:
matrix = np.array([[-1,0,2],[0,1,0],[1,2,-1]])
matrix1 = np.linalg.matrix_power(matrix, 2)

print(matrix1)

[[ 3  4 -4]
 [ 0  1  0]
 [-2  0  3]]


In [10]:
matrix_a = np.array([[5,8,-4],[6,9,-5],[4,7,-3]])
matrix_b = np.array([[3,2,5],[4,-1,3],[9,6,5]])

matrix_c = matrix_a.dot(matrix_b)

print(matrix_c)

[[ 11 -22  29]
 [  9 -27  32]
 [ 13 -17  26]]


In [15]:
matrix = np.array([[2,3,4],[1,0,6],[7,8,9]])
matrix_det = np.linalg.det(matrix)
print(format(matrix_det, '.9g'))

35


In [16]:
matrix = np.array([[2,3,4,1],[1,2,3,4],[3,4,1,2],[4,1,2,3]])
matrix_det = np.linalg.det(matrix)
print(format(matrix_det, '.9g'))

-160


In [17]:
matrix = np.array([[2,1,0,0],[3,2,0,0],[1,1,3,4],[2,-1,2,3]])
matrix_invert = np.linalg.inv(matrix)

print(matrix_invert)

[[  2.  -1.   0.   0.]
 [ -3.   2.   0.   0.]
 [ 31. -19.   3.  -4.]
 [-23.  14.  -2.   3.]]


In [18]:
matrix = np.array([[-2,3,1,-1],[3,2,1,4],[1,2,3,4],[0,2,3,3]])
rank = np.linalg.matrix_rank(matrix)
print(rank)

3


In [21]:
#3x-5y+3z=1
#x+2y+z=4
#2x+7y-z=8

matrix_a = np.array([[3,-5,3],[1,2,1],[2,7,-1]])
matrix_b = np.matrix('1;4;8')

matrix_inv_a = np.linalg.inv(matrix_a)
matrix_dot = matrix_inv_a.dot(matrix_b)

print('A=', matrix_a)
print('B=', matrix_b)
print('A^-1', matrix_inv_a)
print('A^-1 + B = ', matrix_dot)

A= [[ 3 -5  3]
 [ 1  2  1]
 [ 2  7 -1]]
B= [[1]
 [4]
 [8]]
A^-1 [[ 0.27272727 -0.48484848  0.33333333]
 [-0.09090909  0.27272727  0.        ]
 [-0.09090909  0.93939394 -0.33333333]]
A^-1 + B =  [[1.]
 [1.]
 [1.]]


In [22]:
matrix_a = np.array([[3,-5,3],[1,2,1],[2,7,-1]])
matrix_b = np.matrix('1;4;8')

det_a = np.linalg.det(matrix_a)
if det_a != 0:
    a1 = np.matrix(matrix_a)
    a2 = np.matrix(matrix_a)
    a3 = np.matrix(matrix_a)
    a1[:, 0] = matrix_b
    a2[:, 1] = matrix_b
    a3[:, 2] = matrix_b
    x = np.linalg.det(a1)/det_a
    y =np.linalg.det(a2)/det_a
    z= np.linalg.det(a3)/det_a
    print('x=',x.round(3),'y=',y.round(3),'z=',z.round(3)) 
else:
    print("Визначник дорівнює нулю, система не має розв'язків")
    
print(np.linalg.solve(matrix_a,matrix_b).round(3)) 


x= 1.0 y= 1.0 z= 1.0
[[1.]
 [1.]
 [1.]]


In [37]:
#Створіть прямокутну матрицю A, яка має N рядків і M стовпців з випадковими елементами. Визначте середні значення для всіх рядків і стовпців матриці.
n=4
m=n
a=0
i=0
j=0
matrix = np.random.randint(0, 100, size=(n, m))

print(matrix)

for i in range(n):
    for j  in range(n):
        a += matrix[i,j]
    ser = a/n
    print(i + 1, 'рядок середнє: ', ser)
    
for i in range(n):
    for j  in range(n):
        a += matrix[j,i]
    ser = a/n
    print(i + 1, 'стовпчик середнє: ', ser)

[[48 87 21 44]
 [70 32 63 89]
 [33 78 63 46]
 [83 88 55 61]]
1 рядок середнє:  50.0
2 рядок середнє:  113.5
3 рядок середнє:  168.5
4 рядок середнє:  240.25
1 стовпчик середнє:  298.75
2 стовпчик середнє:  370.0
3 стовпчик середнє:  420.5
4 стовпчик середнє:  480.5
